In [9]:
import pandas as pd 
import geopandas as gpd

In [10]:
estacoes_flu_vazoesmedias = pd.read_csv('D:\\BHO_GOIAS\\vazoes_estacoesflu\\Estacoes_FLU_BHO_Goias_V2.xlsx - Atualização dos dados para 2021.csv',sep=',')
estacoes_informacoes = pd.read_csv('D:\\BHO_GOIAS\\vazoes_estacoesflu\\estacoes_filtradas_editadas_pontos_controle_v2.xlsx - estacoes_filtradas_editadas_pon.csv',sep=',')

In [23]:
def transpose_dataset(df,first_column = str):
    df_transposed = df.set_index(first_column).unstack().unstack().reset_index(names=first_column).rename_axis(columns=None)
    return df_transposed

def merge_sheets(estacoes_vazoes,estacoes_infos):
    estacoes_infos['codigo'] = estacoes_infos['codigo'].astype(str)
    estacoes_merge = pd.merge(estacoes_vazoes,estacoes_infos[['nome', 'rio','estacao_qesp_incremental','codigo']],on='codigo')
    estacoes_merge['estacao_qesp_incremental'] = estacoes_merge['estacao_qesp_incremental'].fillna('não consta')
    list_qmed = [ 'adkm2','qmed_jan_(m³/s)',
        'qmed_fev_(m³/s)', 'qmed_mar_(m³/s)', 'qmed_abr_(m³/s)',
        'qmed_mai_(m³/s)', 'qmed_jun_(m³/s)', 'qmed_jul_(m³/s)',
        'qmed_ago_(m³/s)', 'qmed_set_(m³/s)', 'qmed_out_(m³/s)',
        'qmed_nov_(m³/s)', 'qmed_dez_(m³/s)', 'qmed_esp_jan_(l/s/km²)',
        'qmed_esp_fev_(l/s/km²)', 'qmed_esp_mar_(l/s/km²)',
        'qmed_esp_abr_(l/s/km²)', 'qmed_esp_mai_(l/s/km²)',
        'qmed_esp_jun_(l/s/km²)', 'qmed_esp_jul_(l/s/km²)',
        'qmed_esp_ago_(l/s/km²)', 'qmed_esp_set_(l/s/km²)',
        'qmed_esp_out_(l/s/km²)', 'qmed_esp_nov_(l/s/km²)',
        'qmed_esp_dez_(l/s/km²)','q95_jan_(m³/s)',
        'q95_fev_(m³/s)', 'q95_mar_(m³/s)', 'q95_abr_(m³/s)', 'q95_mai_(m³/s)',
        'q95_jun_(m³/s)', 'q95_jul_(m³/s)', 'q95_ago_(m³/s)', 'q95_set_(m³/s)',
        'q95_out_(m³/s)', 'q95_nov_(m³/s)', 'q95_dez_(m³/s)',
        'q95_esp_jan_(l/s/km²)', 'q95_esp_fev_(l/s/km²)',
        'q95_esp_mar_(l/s/km²)', 'q95_esp_abr_(l/s/km²)',
        'q95_esp_mai_(l/s/km²)', 'q95_esp_jun_(l/s/km²)',
        'q95_esp_jul_(l/s/km²)', 'q95_esp_ago_(l/s/km²)',
        'q95_esp_set_(l/s/km²)', 'q95_esp_out_(l/s/km²)',
        'q95_esp_nov_(l/s/km²)', 'q95_esp_dez_(l/s/km²)']

    for column in list_qmed:
        estacoes_merge[column] = estacoes_merge[column].str.replace(',','.').astype(float)

    return estacoes_merge

def calcula_q95esp_incremental(estacoes_dataset):
    '''estacoes_dataset['estacao_qesp_incremental'] = estacoes_dataset['estacao_qesp_incremental'].astype(str)
    estacoes_dataset['q95_jan_(m³/s)'] = estacoes_dataset['q95_jan_(m³/s)'].astype(float)
    estacoes_dataset['q95_fev_(m³/s)'] = estacoes_dataset['q95_fev_(m³/s)'].astype(float)
    estacoes_dataset['q95_mar_(m³/s)'] = estacoes_dataset['q95_mar_(m³/s)'].astype(float)
    estacoes_dataset['q95_abr_(m³/s)'] = estacoes_dataset['q95_abr_(m³/s)'].astype(float)
    estacoes_dataset['q95_mai_(m³/s)'] = estacoes_dataset['q95_mai_(m³/s)'].astype(float)
    estacoes_dataset['q95_jun_(m³/s)'] = estacoes_dataset['q95_jun_(m³/s)'].astype(float)
    estacoes_dataset['q95_jul_(m³/s)'] = estacoes_dataset['q95_jul_(m³/s)'].astype(float)
    estacoes_dataset['q95_ago_(m³/s)'] = estacoes_dataset['q95_ago_(m³/s)'].astype(float)
    estacoes_dataset['q95_set_(m³/s)'] = estacoes_dataset['q95_set_(m³/s)'].astype(float)
    estacoes_dataset['q95_out_(m³/s)'] = estacoes_dataset['q95_out_(m³/s)'].astype(float)
    estacoes_dataset['q95_nov_(m³/s)'] = estacoes_dataset['q95_nov_(m³/s)'].astype(float)
    estacoes_dataset['q95_dez_(m³/s)'] = estacoes_dataset['q95_dez_(m³/s)'].astype(float)'''


    
    
    
    for idx,row in estacoes_dataset.iterrows():
        if row['estacao_qesp_incremental'] == 'não consta':
            estacoes_dataset.at[idx,'q95esp_jan_lskm2'] = ((row['q95_jan_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_fev_lskm2'] = ((row['q95_fev_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_mar_lskm2'] = ((row['q95_mar_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_abr_lskm2'] = ((row['q95_abr_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_mai_lskm2'] = ((row['q95_mai_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_jun_lskm2'] = ((row['q95_jun_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_jul_lskm2'] = ((row['q95_jul_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_ago_lskm2'] = ((row['q95_ago_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_set_lskm2'] = ((row['q95_set_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_out_lskm2'] = ((row['q95_out_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_nov_lskm2'] = ((row['q95_nov_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'q95esp_dez_lskm2'] = ((row['q95_dez_(m³/s)']*1000) / row['adkm2'])

        else:
            lista_estacoes = row['estacao_qesp_incremental'].split(',')
            

            lista_strings = list(map(str.strip,lista_estacoes))
            
            estacoes_montante_consideradas = estacoes_dataset.loc[estacoes_dataset['codigo'].isin(lista_strings)]
            vaz_jan = estacoes_montante_consideradas['q95_jan_(m³/s)'].sum()
            vaz_fev = estacoes_montante_consideradas['q95_fev_(m³/s)'].sum()
            vaz_mar = estacoes_montante_consideradas['q95_mar_(m³/s)'].sum()
            vaz_abr = estacoes_montante_consideradas['q95_abr_(m³/s)'].sum()
            vaz_mai = estacoes_montante_consideradas['q95_mai_(m³/s)'].sum()
            vaz_jun = estacoes_montante_consideradas['q95_jun_(m³/s)'].sum()
            vaz_jul = estacoes_montante_consideradas['q95_jul_(m³/s)'].sum()
            vaz_ago = estacoes_montante_consideradas['q95_ago_(m³/s)'].sum()
            vaz_set = estacoes_montante_consideradas['q95_set_(m³/s)'].sum()
            vaz_out = estacoes_montante_consideradas['q95_out_(m³/s)'].sum()
            vaz_nov = estacoes_montante_consideradas['q95_nov_(m³/s)'].sum()
            vaz_dez = estacoes_montante_consideradas['q95_dez_(m³/s)'].sum()

            areamont = estacoes_montante_consideradas['adkm2'].sum()
            

            estacoes_dataset.at[idx,'q95esp_jan_lskm2'] = ((row['q95_jan_(m³/s)'] - vaz_jan)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_fev_lskm2'] = ((row['q95_fev_(m³/s)'] - vaz_fev)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_mar_lskm2'] = ((row['q95_mar_(m³/s)'] - vaz_mar)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_abr_lskm2'] = ((row['q95_abr_(m³/s)'] - vaz_abr)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_mai_lskm2'] = ((row['q95_mai_(m³/s)'] - vaz_mai)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_jun_lskm2'] = ((row['q95_jun_(m³/s)'] - vaz_jun)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_jul_lskm2'] = ((row['q95_jul_(m³/s)'] - vaz_jul)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_ago_lskm2'] = ((row['q95_ago_(m³/s)'] - vaz_ago)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_set_lskm2'] = ((row['q95_set_(m³/s)'] - vaz_set)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_out_lskm2'] = ((row['q95_out_(m³/s)'] - vaz_out)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_nov_lskm2'] = ((row['q95_nov_(m³/s)'] - vaz_nov)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'q95esp_dez_lskm2'] = ((row['q95_dez_(m³/s)'] - vaz_dez)*1000) / (row['adkm2'] - areamont)



            
            
    return estacoes_dataset


def calcula_qmedesp_incremental(estacoes_dataset):
    '''estacoes_dataset['estacao_qesp_incremental'] = estacoes_dataset['estacao_qesp_incremental'].astype(str)
    estacoes_dataset['q95_jan_(m³/s)'] = estacoes_dataset['q95_jan_(m³/s)'].astype(float)
    estacoes_dataset['q95_fev_(m³/s)'] = estacoes_dataset['q95_fev_(m³/s)'].astype(float)
    estacoes_dataset['q95_mar_(m³/s)'] = estacoes_dataset['q95_mar_(m³/s)'].astype(float)
    estacoes_dataset['q95_abr_(m³/s)'] = estacoes_dataset['q95_abr_(m³/s)'].astype(float)
    estacoes_dataset['q95_mai_(m³/s)'] = estacoes_dataset['q95_mai_(m³/s)'].astype(float)
    estacoes_dataset['q95_jun_(m³/s)'] = estacoes_dataset['q95_jun_(m³/s)'].astype(float)
    estacoes_dataset['q95_jul_(m³/s)'] = estacoes_dataset['q95_jul_(m³/s)'].astype(float)
    estacoes_dataset['q95_ago_(m³/s)'] = estacoes_dataset['q95_ago_(m³/s)'].astype(float)
    estacoes_dataset['q95_set_(m³/s)'] = estacoes_dataset['q95_set_(m³/s)'].astype(float)
    estacoes_dataset['q95_out_(m³/s)'] = estacoes_dataset['q95_out_(m³/s)'].astype(float)
    estacoes_dataset['q95_nov_(m³/s)'] = estacoes_dataset['q95_nov_(m³/s)'].astype(float)
    estacoes_dataset['q95_dez_(m³/s)'] = estacoes_dataset['q95_dez_(m³/s)'].astype(float)'''


    
    
    
    for idx,row in estacoes_dataset.iterrows():
        if row['estacao_qesp_incremental'] == 'não consta':
            estacoes_dataset.at[idx,'qmed_esp_jan_(l/s/km²)'] = ((row['qmed_jan_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_fev_(l/s/km²)'] = ((row['qmed_fev_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_mar_(l/s/km²)'] = ((row['qmed_mar_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_abr_(l/s/km²)'] = ((row['qmed_abr_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_mai_(l/s/km²)'] = ((row['qmed_mai_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_jun_(l/s/km²)'] = ((row['qmed_jun_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_jul_(l/s/km²)'] = ((row['qmed_jul_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_ago_(l/s/km²)'] = ((row['qmed_ago_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_set_(l/s/km²)'] = ((row['qmed_set_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_out_(l/s/km²)'] = ((row['qmed_out_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_nov_(l/s/km²)'] = ((row['qmed_nov_(m³/s)']*1000) / row['adkm2'])
            estacoes_dataset.at[idx,'qmed_esp_dez_(l/s/km²)'] = ((row['qmed_dez_(m³/s)']*1000) / row['adkm2'])

        else:
            lista_estacoes = row['estacao_qesp_incremental'].split(',')
            

            lista_strings = list(map(str.strip,lista_estacoes))
            
            estacoes_montante_consideradas = estacoes_dataset.loc[estacoes_dataset['codigo'].isin(lista_strings)]
            vaz_jan = estacoes_montante_consideradas['qmed_jan_(m³/s)'].sum()
            vaz_fev = estacoes_montante_consideradas['qmed_fev_(m³/s)'].sum()
            vaz_mar = estacoes_montante_consideradas['qmed_mar_(m³/s)'].sum()
            vaz_abr = estacoes_montante_consideradas['qmed_abr_(m³/s)'].sum()
            vaz_mai = estacoes_montante_consideradas['qmed_mai_(m³/s)'].sum()
            vaz_jun = estacoes_montante_consideradas['qmed_jun_(m³/s)'].sum()
            vaz_jul = estacoes_montante_consideradas['qmed_jul_(m³/s)'].sum()
            vaz_ago = estacoes_montante_consideradas['qmed_ago_(m³/s)'].sum()
            vaz_set = estacoes_montante_consideradas['qmed_set_(m³/s)'].sum()
            vaz_out = estacoes_montante_consideradas['qmed_out_(m³/s)'].sum()
            vaz_nov = estacoes_montante_consideradas['qmed_nov_(m³/s)'].sum()
            vaz_dez = estacoes_montante_consideradas['qmed_dez_(m³/s)'].sum()

            areamont = estacoes_montante_consideradas['adkm2'].sum()
            

            estacoes_dataset.at[idx,'qmed_esp_jan_(l/s/km²)'] = ((row['qmed_jan_(m³/s)'] - vaz_jan)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_fev_(l/s/km²)'] = ((row['qmed_fev_(m³/s)'] - vaz_fev)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_mar_(l/s/km²)'] = ((row['qmed_mar_(m³/s)'] - vaz_mar)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_abr_(l/s/km²)'] = ((row['qmed_abr_(m³/s)'] - vaz_abr)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_mai_(l/s/km²)'] = ((row['qmed_mai_(m³/s)'] - vaz_mai)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_jun_(l/s/km²)'] = ((row['qmed_jun_(m³/s)'] - vaz_jun)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_jul_(l/s/km²)'] = ((row['qmed_jul_(m³/s)'] - vaz_jul)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_ago_(l/s/km²)'] = ((row['qmed_ago_(m³/s)'] - vaz_ago)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_set_(l/s/km²)'] = ((row['qmed_set_(m³/s)'] - vaz_set)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_out_(l/s/km²)'] = ((row['qmed_out_(m³/s)'] - vaz_out)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_nov_(l/s/km²)'] = ((row['qmed_nov_(m³/s)'] - vaz_nov)*1000) / (row['adkm2'] - areamont)
            estacoes_dataset.at[idx,'qmed_esp_dez_(l/s/km²)'] = ((row['qmed_dez_(m³/s)'] - vaz_dez)*1000) / (row['adkm2'] - areamont)



            
            
    return estacoes_dataset

In [12]:
estacoes_flu_vaz_transpose = transpose_dataset(estacoes_flu_vazoesmedias,'codigo')
union = merge_sheets(estacoes_flu_vaz_transpose,estacoes_informacoes)
qmedesp_incremental = calcula_qmedesp_incremental(union)
q95esp_incremental = calcula_q95esp_incremental(qmedesp_incremental)

In [21]:
q95esp_incremental

,codigo,adkm2,anoinicio,anofim,anototal,q95_jan_(m³/s),q95_fev_(m³/s),q95_mar_(m³/s),q95_abr_(m³/s),q95_mai_(m³/s),...,q95esp_mar_lskm2,q95esp_abr_lskm2,q95esp_mai_lskm2,q95esp_jun_lskm2,q95esp_jul_lskm2,q95esp_ago_lskm2,q95esp_set_lskm2,q95esp_out_lskm2,q95esp_nov_lskm2,q95esp_dez_lskm2
0,20050000,11200.0,1966,2014,48,83.8,86.8,100.0,79.7,61.2,...,8.928571,7.116071,5.464286,4.428571,3.616071,3.089286,2.955357,3.375000,4.651786,5.883929
1,20100000,1970.0,1964,2021,57,12.7,18.2,23.8,20.7,13.9,...,12.081218,10.507614,7.055838,4.482234,3.238579,2.010152,1.233503,1.517766,3.426396,5.482234
2,20200000,3700.0,1964,2021,57,25.7,39.2,47.7,34.9,23.8,...,12.891892,9.432432,6.432432,4.270270,2.729730,1.716216,0.972973,1.456757,3.162162,5.405405
3,20250000,10600.0,1964,2014,50,94.6,123.0,142.0,99.2,75.6,...,14.300203,8.843813,7.687627,5.734280,3.756592,3.141988,2.772819,3.269777,5.202840,8.600406
4,Hipotética Tocantins 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,60930000,1450.0,1979,2021,42,22.6,23.9,23.4,19.8,19.1,...,16.137931,13.655172,13.172414,12.344828,11.241379,10.413793,9.793103,10.482759,12.137931,12.896552
72,60940000,3190.0,1972,2021,49,50.1,55.4,58.8,48.9,44.0,...,20.344828,16.724138,14.310345,13.333333,12.068966,10.517241,10.344828,11.954023,13.448276,15.402299
73,60950000,6850.0,1972,2021,49,85.1,88.5,91.4,82.9,70.0,...,8.907104,9.289617,7.103825,6.775956,7.076503,6.693989,4.344262,7.377049,7.459016,7.759563
74,60965000,4040.0,1972,2007,35,71.6,69.0,72.8,70.7,58.8,...,18.019802,17.500000,14.554455,12.623762,12.128713,10.742574,10.420792,13.094059,13.638614,15.173267
75,60970000,5220.0,1972,2021,49,79.2,85.7,88.3,79.1,71.2,...,13.135593,7.118644,10.508475,10.847458,7.881356,9.152542,8.983051,4.237288,8.305085,9.067797

In [22]:
filtro = q95esp_incremental['codigo'] == '60680000'

q95esp_incremental.loc[filtro]

,codigo,adkm2,anoinicio,anofim,anototal,q95_jan_(m³/s),q95_fev_(m³/s),q95_mar_(m³/s),q95_abr_(m³/s),q95_mai_(m³/s),...,q95esp_mar_lskm2,q95esp_abr_lskm2,q95esp_mai_lskm2,q95esp_jun_lskm2,q95esp_jul_lskm2,q95esp_ago_lskm2,q95esp_set_lskm2,q95esp_out_lskm2,q95esp_nov_lskm2,q95esp_dez_lskm2
51,60680000,11500.0,1951,2021,70,77.7,96.4,99.0,96.6,69.2,...,6.427406,8.091354,5.458401,4.132137,3.070147,2.200653,1.499184,1.735726,3.477977,6.233279