In [1]:
import pandas as pd
import geopandas as gpd

In [3]:
#bho_mp_teste = gpd.read_file('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\bho_q95_qmed_correc_03-06-2024_final_v3_FINAL.gpkg')

bho_mp_teste = gpd.read_file('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\26-06-2024\\bho_q95_qmed_q95anual_saomarcosok_26-06-2024.gpkg')

In [8]:
bho_mp_teste.info(verbose=True)

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 250987 entries, 0 to 250986
Data columns (total 146 columns):
 #    Column                     Dtype
---   ------                     -----
 0    index                      int64
 1    id                         int64
 2    cobacia                    object
 3    cocursodag                 object
 4    noorigem                   float64
 5    nodestino                  float64
 6    nucomptrec                 float64
 7    nudistbact                 float64
 8    nudistcdag                 float64
 9    nuareacont                 float64
 10   nuareamont                 float64
 11   nogenerico                 object
 12   noligacao                  object
 13   noespecif                  object
 14   noriocomp                  object
 15   nooriginal                 object
 16   cocdadesag                 object
 17   nutrjus                    float64
 18   nudistbacc                 float64
 19   nuareabacc                 float64
 20   nuordemcda                 float64
 21   nucompcda                  float64
 22   nunivotto                  float64
 23   nunivotcda                 float64
 24   nustrahler                 float64
 25   dedominial                 object
 26   dsversao                   object
 27   codigo                     int64
 28   nome                       object
 29   ugh                        object
 30   estacao_qe                 object
 31   cobacia_jus                object
 32   qmed_esp_inc_jan_l/s/km2   float64
 33   qmed_esp_inc_fev_l/s/km2   float64
 34   qmed_esp_inc_mar_l/s/km2   float64
 35   qmed_esp_inc_abr_l/s/km2   float64
 36   qmed_esp_inc_mai_l/s/km2   float64
 37   qmed_esp_inc_jun_l/s/km2   float64
 38   qmed_esp_inc_jul_l/s/km2   float64
 39   qmed_esp_inc_ago_l/s/km2   float64
 40   qmed_esp_inc_set_l/s/km2   float64
 41   qmed_esp_inc_out_l/s/km2   float64
 42   qmed_esp_inc_nov_l/s/km2   float64
 43   qmed_esp_inc_dez_l/s/km2   float64
 44   q95esp_inc_jan_l/s/km2     float64
 45   q95esp_inc_fev_l/s/km2     float64
 46   q95esp_inc_mar_l/s/km2     float64
 47   q95esp_inc_abr_l/s/km2     float64
 48   q95esp_inc_mai_l/s/km2     float64
 49   q95esp_inc_jun_l/s/km2     float64
 50   q95esp_inc_jul_l/s/km2     float64
 51   q95esp_inc_ago_l/s/km2     float64
 52   q95esp_inc_set_l/s/km2     float64
 53   q95esp_inc_out_l/s/km2     float64
 54   q95esp_inc_nov_l/s/km2     float64
 55   q95esp_inc_dez_l/s/km2     float64
 56   q95anualesp_inc_l/s/km2    float64
 57   q95_jan_ls                 float64
 58   q95_fev_ls                 float64
 59   q95_mar_ls                 float64
 60   q95_abr_ls                 float64
 61   q95_mai_ls                 float64
 62   q95_jun_ls                 float64
 63   q95_jul_ls                 float64
 64   q95_ago_ls                 float64
 65   q95_set_ls                 float64
 66   q95_out_ls                 float64
 67   q95_nov_ls                 float64
 68   q95_dez_ls                 float64
 69   vaz_increment_jan_ls       float64
 70   vaz_increment_fev_ls       float64
 71   vaz_increment_mar_ls       float64
 72   vaz_increment_abr_ls       float64
 73   vaz_increment_mai_ls       float64
 74   vaz_increment_jun_ls       float64
 75   vaz_increment_jul_ls       float64
 76   vaz_increment_ago_ls       float64
 77   vaz_increment_set_ls       float64
 78   vaz_increment_out_ls       float64
 79   vaz_increment_nov_ls       float64
 80   vaz_increment_dez_ls       float64
 81   new_q95_jan_ls             float64
 82   new_q95_fev_ls             float64
 83   new_q95_mar_ls             float64
 84   new_q95_abr_ls             float64
 85   new_q95_mai_ls             float64
 86   new_q95_jun_ls             float64
 87   new_q95_jul_ls             float64
 88   new_q95_ago_ls             float64
 89   new_q95_set_ls             float64
 90   new_q95_out_ls             float64
 91   new_q95_nov_ls             float64
 92   new_q95_dez_ls             float64
 93   qmed_jan_ls                float64
 94   qmed_fev_ls                float64
 95   qmed_mar_ls                float64
 96   qmed_abr_ls                float64
 97   qmed_mai_ls                float64
 98   qmed_jun_ls                float64
 99   qmed_jul_ls                float64
 100  qmed_ago_ls                float64
 101  qmed_set_ls                float64
 102  qmed_out_ls                float64
 103  qmed_nov_ls                float64
 104  qmed_dez_ls                float64
 105  vaz_qmed_increment_jan_ls  float64
 106  vaz_qmed_increment_fev_ls  float64
 107  vaz_qmed_increment_mar_ls  float64
 108  vaz_qmed_increment_abr_ls  float64
 109  vaz_qmed_increment_mai_ls  float64
 110  vaz_qmed_increment_jun_ls  float64
 111  vaz_qmed_increment_jul_ls  float64
 112  vaz_qmed_increment_ago_ls  float64
 113  vaz_qmed_increment_set_ls  float64
 114  vaz_qmed_increment_out_ls  float64
 115  vaz_qmed_increment_nov_ls  float64
 116  vaz_qmed_increment_dez_ls  float64
 117  new_qmed_jan_ls            float64
 118  new_qmed_fev_ls            float64
 119  new_qmed_mar_ls            float64
 120  new_qmed_abr_ls            float64
 121  new_qmed_mai_ls            float64
 122  new_qmed_jun_ls            float64
 123  new_qmed_jul_ls            float64
 124  new_qmed_ago_ls            float64
 125  new_qmed_set_ls            float64
 126  new_qmed_out_ls            float64
 127  new_qmed_nov_ls            float64
 128  new_qmed_dez_ls            float64
 129  q95_anual                  float64
 130  vaz_q95_anual_incremental  float64
 131  situacao_trecho            object
 132  new_q95_anual_ls           float64
 133  geometry                   geometry
 134  verificacao_jan            object
 135  verificacao_fev            object
 136  verificacao_mar            object
 137  verificacao_abr            object
 138  verificacao_mai            object
 139  verificacao_jun            object
 140  verificacao_jul            object
 141  verificacao_ago            object
 142  verificacao_set            object
 143  verificacao_out            object
 144  verificacao_nov            object
 145  verificacao_dez            object
dtypes: float64(115), geometry(1), int64(3), object(27)
memory usage: 279.6+ MB

In [4]:
import numpy as np

for idx, row in bho_mp_teste.iterrows():
    tributarios = bho_mp_teste.loc[bho_mp_teste['nodestino'] == row['noorigem']]

    soma_jan = tributarios['new_q95_jan_ls'].sum()
    soma_fev = tributarios['new_q95_fev_ls'].sum()
    soma_mar = tributarios['new_q95_mar_ls'].sum()
    soma_abr = tributarios['new_q95_abr_ls'].sum()
    soma_mai = tributarios['new_q95_mai_ls'].sum()
    soma_jun = tributarios['new_q95_jun_ls'].sum()
    soma_jul = tributarios['new_q95_jul_ls'].sum()
    soma_ago = tributarios['new_q95_ago_ls'].sum()
    soma_set = tributarios['new_q95_set_ls'].sum()
    soma_out = tributarios['new_q95_out_ls'].sum()
    soma_nov = tributarios['new_q95_nov_ls'].sum()
    soma_dez = tributarios['new_q95_dez_ls'].sum()


    jan = soma_jan + row['vaz_increment_jan_ls']
    fev = soma_fev + row['vaz_increment_fev_ls']
    mar = soma_mar + row['vaz_increment_mar_ls']
    abr = soma_abr + row['vaz_increment_abr_ls']
    mai = soma_mai + row['vaz_increment_mai_ls']
    jun = soma_jun + row['vaz_increment_jun_ls']
    jul = soma_jul + row['vaz_increment_jul_ls']
    ago = soma_ago + row['vaz_increment_ago_ls']
    set = soma_set + row['vaz_increment_set_ls']
    out = soma_out + row['vaz_increment_out_ls']
    nov = soma_nov + row['vaz_increment_nov_ls']
    dez = soma_dez + row['vaz_increment_dez_ls']

    bho_mp_teste.at[idx,'verificacao_jan'] = np.isclose(jan,bho_mp_teste.at[idx,'new_q95_jan_ls'])
    bho_mp_teste.at[idx,'verificacao_fev'] = np.isclose(fev,bho_mp_teste.at[idx,'new_q95_fev_ls'])
    bho_mp_teste.at[idx,'verificacao_mar'] = np.isclose(mar,bho_mp_teste.at[idx,'new_q95_mar_ls'])
    bho_mp_teste.at[idx,'verificacao_abr'] = np.isclose(abr,bho_mp_teste.at[idx,'new_q95_abr_ls'])
    bho_mp_teste.at[idx,'verificacao_mai'] = np.isclose(mai,bho_mp_teste.at[idx,'new_q95_mai_ls'])
    bho_mp_teste.at[idx,'verificacao_jun'] = np.isclose(jun,bho_mp_teste.at[idx,'new_q95_jun_ls'])
    bho_mp_teste.at[idx,'verificacao_jul'] = np.isclose(jul,bho_mp_teste.at[idx,'new_q95_jul_ls'])
    bho_mp_teste.at[idx,'verificacao_ago'] = np.isclose(ago,bho_mp_teste.at[idx,'new_q95_ago_ls'])
    bho_mp_teste.at[idx,'verificacao_set'] = np.isclose(set,bho_mp_teste.at[idx,'new_q95_set_ls'])
    bho_mp_teste.at[idx,'verificacao_out'] = np.isclose(out,bho_mp_teste.at[idx,'new_q95_out_ls'])
    bho_mp_teste.at[idx,'verificacao_nov'] = np.isclose(nov,bho_mp_teste.at[idx,'new_q95_nov_ls'])
    bho_mp_teste.at[idx,'verificacao_dez'] = np.isclose(dez,bho_mp_teste.at[idx,'new_q95_dez_ls'])

In [5]:
bho_mp_teste

,index,id,cobacia,cocursodag,noorigem,nodestino,nucomptrec,nudistbact,nudistcdag,nuareacont,...,verificacao_mar,verificacao_abr,verificacao_mai,verificacao_jun,verificacao_jul,verificacao_ago,verificacao_set,verificacao_out,verificacao_nov,verificacao_dez
0,0,1,69446983,6944698,1233401.0,1233433.0,5.238262,2099.160246,0.302869,4.926527,...,True,True,True,True,True,True,True,True,True,True
1,1,2,69449223,6944922,1233938.0,1233934.0,3.122452,2110.469471,1.200575,4.279441,...,True,True,True,True,True,True,True,True,True,True
2,2,3,6944213,69442,1233533.0,1238486.0,6.479363,2027.080923,0.399669,9.907925,...,True,True,True,True,True,True,True,True,True,True
3,3,4,69423782,69423782,1205391.0,1205392.0,2.926657,2060.556293,0.000000,3.843337,...,True,True,True,True,True,True,True,True,True,True
4,4,5,69441676,69441676,1238396.0,1238401.0,3.461337,2042.237401,0.000000,5.883635,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250982,250982,250983,69997125,6999712,3550028.0,3550027.0,1.061870,2756.691441,2.622813,6.131939,...,True,True,True,True,True,True,True,True,True,True
250983,250983,250984,6999826,6999826,3550259.0,3550258.0,1.091829,2819.325483,0.000000,4.918330,...,True,True,True,True,True,True,True,True,True,True
250984,250984,250985,6999829,699982,3550276.0,3550275.0,1.178342,2820.859603,5.265518,5.785314,...,True,True,True,True,True,True,True,True,True,True
250985,250985,250986,6999852,6999852,3550334.0,3550332.0,1.919439,2819.110840,0.000000,9.584848,...,True,True,True,True,True,True,True,True,True,True
250986,250986,250987,6999519,6,3566926.0,3566925.0,0.060910,2710.214631,2710.214631,0.004944,...,True,True,True,True,True,True,True,True,True,True

In [11]:
bho_mp_teste['verificacao_mar'].value_counts()

verificacao_mar
True     248032
False      2955
Name: count, dtype: int64

In [12]:
errados = bho_mp_teste.loc[bho_mp_teste['verificacao_jan']==False]
errados


errados.to_csv('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\26-06-2024\\trechos_comerro.csv')