In [30]:
import pandas as pd
import geopandas as gpd

In [31]:
#bho_mp_teste = gpd.read_file('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\bho_q95_qmed_correc_03-06-2024_final_v3_FINAL.gpkg')

bho_mp_teste = pd.read_csv('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\bho_q95_qmed_correc_03-06-2024_final_v3_FINAL.csv')

C:\Users\matheus.cgomes\AppData\Local\Temp\ipykernel_10388\2995438525.py:3: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  bho_mp_teste = pd.read_csv('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\bho_q95_qmed_correc_03-06-2024_final_v3_FINAL.csv')

In [32]:
import numpy as np

for idx, row in bho_mp_teste.iterrows():
    tributarios = bho_mp_teste.loc[bho_mp_teste['nodestino'] == row['noorigem']]

    soma_jan = tributarios['new_q95_jan_ls'].sum()
    soma_fev = tributarios['new_q95_fev_ls'].sum()
    soma_mar = tributarios['new_q95_mar_ls'].sum()
    soma_abr = tributarios['new_q95_abr_ls'].sum()
    soma_mai = tributarios['new_q95_mai_ls'].sum()
    soma_jun = tributarios['new_q95_jun_ls'].sum()
    soma_jul = tributarios['new_q95_jul_ls'].sum()
    soma_ago = tributarios['new_q95_ago_ls'].sum()
    soma_set = tributarios['new_q95_set_ls'].sum()
    soma_out = tributarios['new_q95_out_ls'].sum()
    soma_nov = tributarios['new_q95_nov_ls'].sum()
    soma_dez = tributarios['new_q95_dez_ls'].sum()


    jan = soma_jan + row['vaz_increment_jan_ls']
    fev = soma_fev + row['vaz_increment_fev_ls']
    mar = soma_mar + row['vaz_increment_mar_ls']
    abr = soma_abr + row['vaz_increment_abr_ls']
    mai = soma_mai + row['vaz_increment_mai_ls']
    jun = soma_jun + row['vaz_increment_jun_ls']
    jul = soma_jul + row['vaz_increment_jul_ls']
    ago = soma_ago + row['vaz_increment_ago_ls']
    set = soma_set + row['vaz_increment_set_ls']
    out = soma_out + row['vaz_increment_out_ls']
    nov = soma_nov + row['vaz_increment_nov_ls']
    dez = soma_dez + row['vaz_increment_dez_ls']

    bho_mp_teste.at[idx,'verificacao_jan'] = np.isclose(jan,bho_mp_teste.at[idx,'new_q95_jan_ls'])
    bho_mp_teste.at[idx,'verificacao_fev'] = np.isclose(fev,bho_mp_teste.at[idx,'new_q95_fev_ls'])
    bho_mp_teste.at[idx,'verificacao_mar'] = np.isclose(mar,bho_mp_teste.at[idx,'new_q95_mar_ls'])
    bho_mp_teste.at[idx,'verificacao_abr'] = np.isclose(abr,bho_mp_teste.at[idx,'new_q95_abr_ls'])
    bho_mp_teste.at[idx,'verificacao_mai'] = np.isclose(mai,bho_mp_teste.at[idx,'new_q95_mai_ls'])
    bho_mp_teste.at[idx,'verificacao_jun'] = np.isclose(jun,bho_mp_teste.at[idx,'new_q95_jun_ls'])
    bho_mp_teste.at[idx,'verificacao_jul'] = np.isclose(jul,bho_mp_teste.at[idx,'new_q95_jul_ls'])
    bho_mp_teste.at[idx,'verificacao_ago'] = np.isclose(ago,bho_mp_teste.at[idx,'new_q95_ago_ls'])
    bho_mp_teste.at[idx,'verificacao_set'] = np.isclose(set,bho_mp_teste.at[idx,'new_q95_set_ls'])
    bho_mp_teste.at[idx,'verificacao_out'] = np.isclose(out,bho_mp_teste.at[idx,'new_q95_out_ls'])
    bho_mp_teste.at[idx,'verificacao_nov'] = np.isclose(nov,bho_mp_teste.at[idx,'new_q95_nov_ls'])
    bho_mp_teste.at[idx,'verificacao_dez'] = np.isclose(dez,bho_mp_teste.at[idx,'new_q95_dez_ls'])

In [36]:
bho_mp_teste

,Unnamed: 0,id,cobacia,cocursodag,noorigem,nodestino,nucomptrec,nudistbact,nudistcdag,nuareacont,...,verificacao_mar,verificacao_abr,verificacao_mai,verificacao_jun,verificacao_jul,verificacao_ago,verificacao_set,verificacao_out,verificacao_nov,verificacao_dez
0,0,1,69446983,6944698,1233401.0,1233433.0,5.238262,2099.160246,0.302869,4.926527,...,True,True,True,True,True,True,True,True,True,True
1,1,2,69449223,6944922,1233938.0,1233934.0,3.122452,2110.469471,1.200575,4.279441,...,True,True,True,True,True,True,True,True,True,True
2,2,3,6944213,69442,1233533.0,1238486.0,6.479363,2027.080923,0.399669,9.907925,...,True,True,True,True,True,True,True,True,True,True
3,3,4,69423782,69423782,1205391.0,1205392.0,2.926657,2060.556293,0.000000,3.843337,...,True,True,True,True,True,True,True,True,True,True
4,4,5,69441676,69441676,1238396.0,1238401.0,3.461337,2042.237401,0.000000,5.883635,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250982,250982,250983,69997125,6999712,3550028.0,3550027.0,1.061870,2756.691441,2.622813,6.131939,...,True,True,True,True,True,True,True,True,True,True
250983,250983,250984,6999826,6999826,3550259.0,3550258.0,1.091829,2819.325483,0.000000,4.918330,...,True,True,True,True,True,True,True,True,True,True
250984,250984,250985,6999829,699982,3550276.0,3550275.0,1.178342,2820.859603,5.265518,5.785314,...,True,True,True,True,True,True,True,True,True,True
250985,250985,250986,6999852,6999852,3550334.0,3550332.0,1.919439,2819.110840,0.000000,9.584848,...,True,True,True,True,True,True,True,True,True,True
250986,250986,250987,6999519,6,3566926.0,3566925.0,0.060910,2710.214631,2710.214631,0.004944,...,True,True,True,True,True,True,True,True,True,True

In [39]:
bho_mp_teste['verificacao_jan'].value_counts()

verificacao_jan
True     250722
False       265
Name: count, dtype: int64

In [61]:
errados = bho_mp_teste.loc[bho_mp_teste['verificacao_jan']==False]


errados.to_csv('D:\\matheus.cgomes\\Documentos\\GitHub\\gis_automations\\data\\teste_mp_12-06-2024\\trechos_comerro.csv')